interface IProcessedTransaction {
    POSTransactionId?: string;
    TransactionId?: string;
    Status?: string;
    Currency?: string,
    TransactionTime?: string;
}

/**
 * Represtents payee transaction included in a payment transaction
 */
export default class ProcessedTransaction {

    /**
     * The unique identifier of the transaction at the shop that started the payment.
     */
    POSTransactionId: string = "";

    /**
     * The unique identifier of the transaction generated by the Barion system.
     */
    TransactionId: string = "";

    /**
     * The current status of the payment containing the transaction.
     */
    Status: string = "";

    /**
     * The 3 character ISO 4217 currency code of the transaction.
     */
    Currency: string = "";

    /**
     * The timestamp of the transaction.
     */
    TransactionTime: string = "";

    constructor(o?: IProcessedTransaction | any) {
         if (o) {
            this.POSTransactionId = o.POSTransactionId || "";
            this.TransactionId = o.TransactionId || "";
            this.Status = o.Status || "";
            this.Currency = o.Currency || "";
            this.TransactionTime = o.TransactionTime || "";
         }
     }
}